import { ScreenDefinition } from './types';

export const SCREENS: ScreenDefinition[] = [
  // -------------------------------------------------------------
  // CUSTOMER STOREFRONT SCREENS (12)
  // -------------------------------------------------------------
  {
    id: 'storefront-home',
    title: 'Storefront Homepage',
    category: 'storefront',
    path: '/home',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_homepage_refined/code.html',
    description: 'Hero promotional banner, instant search, sample product grid, botanical wellness accents',
    defaultViewport: 'mobile',
    aliases: ['home', '/', 'storefront', 'shop-home'],
  },
  {
    id: 'storefront-products',
    title: 'Product Catalog & Filters',
    category: 'storefront',
    path: '/products',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_products_page_enhanced/code.html',
    description: 'Product catalog with search, category filtering, responsive product grid, and variant modal',
    defaultViewport: 'mobile',
    aliases: ['products', 'shop', '/products'],
  },
  {
    id: 'storefront-product-detail',
    title: 'Product Detail (390px)',
    category: 'storefront',
    path: '/products/1',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_product_detail_page_390px_mobile_frame/code.html',
    description: 'Hero carousel, health benefits, ingredients, variant selectors, add to cart & buy now',
    defaultViewport: 'mobile',
    aliases: ['product-detail', '/products/1', '/products/2'],
  },
  {
    id: 'storefront-cart',
    title: 'Shopping Cart & Coupon',
    category: 'storefront',
    path: '/cart',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_cart_page_with_coupon_ui/code.html',
    description: 'Item qty manager, coupon code voucher applicator, order subtotal, proceed to checkout',
    defaultViewport: 'mobile',
    aliases: ['cart', '/cart'],
  },
  {
    id: 'storefront-checkout',
    title: 'Checkout & Payment',
    category: 'storefront',
    path: '/checkout',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_checkout_page_true_390px_mobile_frame/code.html',
    description: 'Delivery address, shipping selection, PromptPay / credit card methods, order confirmation',
    defaultViewport: 'mobile',
    aliases: ['checkout', '/checkout'],
  },
  {
    id: 'storefront-order-success',
    title: 'Order Success & Confirmation',
    category: 'storefront',
    path: '/order-success',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_order_success_page/code.html',
    description: 'Order reference number, delivery status timeline, order item recap, home redirect',
    defaultViewport: 'mobile',
    aliases: ['order-success', '/order-success'],
  },
  {
    id: 'storefront-login',
    title: 'Customer Login',
    category: 'storefront',
    path: '/login',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_login_page/code.html',
    description: 'Email/password authentication, remember credentials, registration link',
    defaultViewport: 'mobile',
    aliases: ['login', 'customer-login', '/login'],
  },
  {
    id: 'storefront-register',
    title: 'Customer Register',
    category: 'storefront',
    path: '/register',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_register_page/code.html',
    description: 'Account sign up form, phone verification, terms and conditions consent',
    defaultViewport: 'mobile',
    aliases: ['register', '/register'],
  },
  {
    id: 'storefront-account',
    title: 'Account Overview',
    category: 'storefront',
    path: '/account',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_account_overview_page/code.html',
    description: 'Member card, quick order shortcuts, saved addresses, payment methods, logout',
    defaultViewport: 'mobile',
    aliases: ['account', 'account-overview', '/account'],
  },
  {
    id: 'storefront-profile',
    title: 'Customer Profile Edit',
    category: 'storefront',
    path: '/account/profile',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_customer_profile_page/code.html',
    description: 'Profile avatar, personal details, contact number, birthdate, address management',
    defaultViewport: 'mobile',
    aliases: ['profile', 'profile-section', '/account/profile'],
  },
  {
    id: 'storefront-my-orders',
    title: 'My Orders History',
    category: 'storefront',
    path: '/account/orders',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_my_orders_page/code.html',
    description: 'Categorized orders tabs (All, To Pay, Shipping, Completed, Cancelled), tracking info',
    defaultViewport: 'mobile',
    aliases: ['my-orders', 'orders-section', '/account/orders'],
  },
  {
    id: 'storefront-order-detail',
    title: 'Customer Order Detail',
    category: 'storefront',
    path: '/account/orders/detail',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_mobile_order_detail_page/code.html',
    description: 'Package tracking status, live step progress, parcel delivery carrier, item list',
    defaultViewport: 'mobile',
    aliases: ['order-detail', '/account/orders/pending-sample', '/account/orders/[orderId]'],
  },

  // -------------------------------------------------------------
  // ADMIN & SUPER ADMIN BACK OFFICE SCREENS (16)
  // -------------------------------------------------------------
  {
    id: 'admin-login',
    title: 'Admin Console Login',
    category: 'admin',
    path: '/admin/login',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_super_admin_login_page_refined_layout/code.html',
    description: 'Back office secure authentication with role enforcement and modern botanical layout',
    defaultViewport: 'desktop',
    aliases: ['admin-login', 'admin/login', '/admin/login'],
  },
  {
    id: 'admin-dashboard',
    title: 'Executive Admin Dashboard',
    category: 'admin',
    path: '/admin/dashboard',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_responsive_admin_dashboard_with_date_filtering/code.html',
    description: 'KPI metric cards, revenue trends, date interval filters, recent order dispatch overview',
    defaultViewport: 'desktop',
    aliases: ['dashboard', 'admin-dashboard', 'soulmate-admin-dashboard', '/admin/dashboard'],
  },
  {
    id: 'admin-products',
    title: 'Products Management',
    category: 'admin',
    path: '/admin/products',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_products_list/code.html',
    description: 'Product inventory listing, stock indicators, category filters, quick edit/delete actions',
    defaultViewport: 'desktop',
    aliases: ['admin-products', 'soulmate-admin-products', '/admin/products'],
  },
  {
    id: 'admin-add-product',
    title: 'Add New Product',
    category: 'admin',
    path: '/admin/products/new',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_add_product/code.html',
    description: 'Product form: Thai/English titles, SKU, pricing, category, botanical specs, image dropzone',
    defaultViewport: 'desktop',
    aliases: ['products/new', 'admin-products/new', '/admin/products/new'],
  },
  {
    id: 'admin-edit-product',
    title: 'Edit Product',
    category: 'admin',
    path: '/admin/products/edit',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_edit_product/code.html',
    description: 'Detailed product editor: status switcher, tiered pricing, ingredients, gallery preview',
    defaultViewport: 'desktop',
    aliases: ['products/edit', 'admin-edit-product', '/admin/products/edit'],
  },
  {
    id: 'admin-orders',
    title: 'Orders Management',
    category: 'admin',
    path: '/admin/orders',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_orders_list/code.html',
    description: 'Fulfillment workflow, order filtering by payment status, shipping batch actions',
    defaultViewport: 'desktop',
    aliases: ['admin-orders', 'soulmate-admin-orders', '/admin/orders'],
  },
  {
    id: 'admin-order-detail',
    title: 'Admin Order Detail',
    category: 'admin',
    path: '/admin/orders/detail',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_order_detail/code.html',
    description: 'Order inspection: customer address, payment proof verification, status update selector',
    defaultViewport: 'desktop',
    aliases: ['admin-order-detail', '/admin/orders/detail', 'order-detail-admin'],
  },
  {
    id: 'admin-customers',
    title: 'Customers Directory',
    category: 'admin',
    path: '/admin/customers',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_customers_list/code.html',
    description: 'Customer records, lifetime spending, total orders, active account statuses',
    defaultViewport: 'desktop',
    aliases: ['customers', 'admin-customers', 'soulmate-admin-customers', '/admin/customers'],
  },
  {
    id: 'admin-customer-detail',
    title: 'Admin Customer Detail',
    category: 'admin',
    path: '/admin/customers/detail',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_customer_detail/code.html',
    description: 'Customer profile history, purchase habits, registered shipping addresses',
    defaultViewport: 'desktop',
    aliases: ['admin-customer-detail', '/admin/customers/detail'],
  },
  {
    id: 'admin-coupons',
    title: 'Coupons & Discounts',
    category: 'admin',
    path: '/admin/coupons',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_coupons_list/code.html',
    description: 'Discount codes list, percentage / fixed amount tags, usage counts, validity status',
    defaultViewport: 'desktop',
    aliases: ['coupons', 'admin-coupons', 'soulmate-admin-coupons-list', '/admin/coupons'],
  },
  {
    id: 'admin-add-coupon',
    title: 'Add New Coupon',
    category: 'admin',
    path: '/admin/coupons/new',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_add_coupon/code.html',
    description: 'Coupon creation form: code generation, minimum order value, discount limit, schedule',
    defaultViewport: 'desktop',
    aliases: ['coupons/new', 'admin-add-coupon', '/admin/coupons/new'],
  },
  {
    id: 'admin-edit-coupon',
    title: 'Edit Coupon',
    category: 'admin',
    path: '/admin/coupons/edit',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_edit_coupon/code.html',
    description: 'Modify promotional discount parameters, active toggle, validity dates extension',
    defaultViewport: 'desktop',
    aliases: ['coupons/edit', 'admin-edit-coupon', '/admin/coupons/edit'],
  },
  {
    id: 'admin-banners',
    title: 'Promotional Banners List',
    category: 'admin',
    path: '/admin/banners',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_banners_list/code.html',
    description: 'Homepage CMS banner slots, carousel sorting, active/draft toggle, banner preview',
    defaultViewport: 'desktop',
    aliases: ['banners', 'admin-banners', 'soulmate-admin-banners', '/admin/banners'],
  },
  {
    id: 'admin-add-banner',
    title: 'Add New Banner',
    category: 'admin',
    path: '/admin/banners/new',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_add_banner/code.html',
    description: 'Banner CMS creator: slot positioning, link action routing, high-res graphic upload',
    defaultViewport: 'desktop',
    aliases: ['banners/new', 'admin-add-banner', '/admin/banners/new'],
  },
  {
    id: 'admin-edit-banner',
    title: 'Edit Banner',
    category: 'admin',
    path: '/admin/banners/edit',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_admin_edit_banner/code.html',
    description: 'Update banner image asset, modify schedule, adjust click-through target',
    defaultViewport: 'desktop',
    aliases: ['banners/edit', 'admin-edit-banner', '/admin/banners/edit'],
  },
  {
    id: 'admin-settings',
    title: 'Super Admin Settings',
    category: 'admin',
    path: '/admin/settings',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_super_admin_settings/code.html',
    description: 'Store metadata, payment gateway configs, notification channels, roles & permissions',
    defaultViewport: 'desktop',
    aliases: ['settings', 'admin-settings', 'soulmate-admin-settings', '/admin/settings'],
  },

  // -------------------------------------------------------------
  // BRAND ASSETS & SPECIFICATION (1)
  // -------------------------------------------------------------
  {
    id: 'brand-logo',
    title: 'Official Brand Logo',
    category: 'brand',
    path: '/brand/logo',
    htmlPath: '/stitch_soulmate_e_commerce/soulmate_brand_logo/code.html',
    description: 'Official high-resolution SOULMATE Health & Beauty vector logo asset',
    defaultViewport: 'mobile',
    aliases: ['brand-logo', 'logo'],
  },
];

export function findScreenByPathOrAlias(inputPath: string): ScreenDefinition | undefined {
  const clean = inputPath.trim().replace(/^#\/?/, '').replace(/^\//, '');
  if (!clean || clean === 'home') {
    return SCREENS[0];
  }
  
  return SCREENS.find((s) => {
    if (s.id === clean) return true;
    if (s.path.replace(/^\//, '') === clean) return true;
    if (s.aliases.some((a) => a.replace(/^\//, '').toLowerCase() === clean.toLowerCase())) return true;
    return false;
  });
}
